name: Azure deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t docker.pkg.github.com/ilslv/trlogic_task/azure:${{ github.sha }}
        docker push docker.pkg.github.com/ilslv/trlogic_task/azure:${{ github.sha }}    

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'bsu-lab4'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'docker.pkg.github.com/ilslv/trlogic_task/azure:${{ github.sha }}'
